backend:
  name: git-gateway
  branch: develop

site_url: https://ope.technology

media_folder: static/img
public_folder: img

publish_mode: editorial_workflow

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{year}}/{{month}}/{{day}}/{{title}}
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text, required: false }
      - {
          name: featuredImage,
          label: Featured Image,
          widget: image,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }

  - name: projects
    label: Projects
    folder: content/projects
    preview_path: project/{{title}}
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text, required: false }
      - {
          name: featuredImage,
          label: Featured Image,
          widget: image,
          hint: image should be square (min 500px x 500px),
        }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - label: About Page
        name: about
        file: content/pages/about.md
        fields:
          - { name: body, label: Body, widget: markdown }
